# 예외처리


![java](/Image/java_language/java2.png)


## Error

* 메모리 부족, stack overflow와 같이 일단 발생하면 복구할 수 없는 상황.
* 프로그램의 비 정상적 종료를 막을 수 없음. -> 디버깅 필요.
* 코드 자체를 전면 수정하여 고쳐야 한다.


## Exception

* 읽으려는 파일이 없거나, 네트워크 연결이 안 되는 등 수습이될 수 있는 비교적 상태가 약한 것들.
* 프로그램 코드에 의해 수습될 수 없는 상황.


## 예외처리란?

* Exception Handling

* 예외 발생 시 프로그램의 비 정상 종료를 막고 정상적인 실행상태를 유지하는 것.
* 예외의 감지 및 예외 발생 시 동작할 코드 작성 필요.


## 예외 클래스의 계층

### Checked Exception
> 예외에 대한 대처 코드가 없으면 컴파일이 진행되지 않음.

* 빨간줄 뜨는 것!!
* 🔥🔥🔥 예외처리가 필수!!!  🔥🔥🔥


### Unchecked Exception (RuntimeException의 하위 클래스)
> 예외에 대한 대처 코드가 없더라도 컴파일은 진행됨.

* 개발자의 실수...
* 코드를 돌려봐야 에러를 알 수 있고, 에러가 날수도 안날수도 있다.
* ex ) 1/0 , 배열의 초과 등...
* 🔥🔥🔥 예외처리가 필수는 아니지만, 안하면 개발자만 손해! 🔥🔥🔥


## Throwable의 주요 메서드

| 메서드 |  설명 |
|-|-|
|public String getMessage | 발생된 예외에 대한 구체적인 메세지를 반환|
|public Throwable getCause() | 예외의 원인이 되는 Throwable 객체 또는 null을 반환|
|public void printStackTrace() | 예외가 발생된 메서드가 호출되기까지 메서드 호출 스택을 출력. 디버깅의 수단으로 주로 사용된다.|



## try-catch-finally 구문

* finally는 예외 발생 여부와 상관없이 언제나 실행.
* 중간에 return 을 만나는 경우에도 finally블록을 먼저 실행 후 return 실행.

```java
try{
    
}catch(Exception e){

}finally{
    //try 블록에서 접근했던 System자원의 안전한 원상복구.
    // 특히, 입출력시에 try구문에서 입출력에 대한 통로를 열게되는데, 
    // 그걸 닫는 역할을 finally에 적어줌으로써 정상적인 종료를 만들어냄.
}

```

```java
public class Main{
    public static void main(String[] args){

        int i = 1;

        try{
            System.out.println("1");
            int n = 1/i;            // 에러가 뜨지 않을때.
            System.out.println("2");
            return;             
            // 종료 직전에 finally 구문을 실행후 종료.
        }catch(ArithmeticException e){
            System.out.println("3");
        }finally{
            System.out.println("4");
        }
        System.out.println("5");

        /**
         * 출력결과
         *  1
         *  2
         *  4
         */
    }
}

```

```java
public class Main{
    public static void main(String[] args){

        int i = 0;

        try{
            System.out.println("1");
            int n = 1/i;            // 에러 발생!
            System.out.println("2");
            return;
        }catch(ArithmeticException e){
            System.out.println("3");
        }finally{
            System.out.println("4");
        }
        System.out.println("5");

        /**
         * 출력결과
         *  1
         *  3
         *  4
         *  5
         */
    }
}

```




## throws로 예외 던지기

### checkedException은 반드시 throws로 처리를 해주어야 함. (혹은 그 즉시 처리 해주어야함.)

```java
public class Main{

    static void method2() throws ClassNotFoundException{
        Class.forName("heesootory");
    }

    static void method1() throws ClassNotFoundException{
        method2();
    }

    public static void main(String[] args){

        try{
            method1();
        }catch(ClassNotFoundException e){
            e.printStackTrace();
        }


        
        /**
         * 출력결과
         * java.lang.ClassNotFoundException: heesootory
         * 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
         * 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
         * 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
         * 	at java.base/java.lang.Class.forName0(Native Method)
         * 	at java.base/java.lang.Class.forName(Class.java:315)
         * 	at Main.method2(Main.java:8)
         * 	at Main.method1(Main.java:12)
         * 	at Main.main(Main.java:18)
         */


    }
}
```


```java
public class Main{

    static void method2() throws ClassNotFoundException{
        Class.forName("heesootory");
    }

    static void method1() throws Exception{
        method2();
    }

    public static void main(String[] args){

        try{
            method1();
        }catch(ClassNotFoundException e){
            e.printStackTrace();
        }catch(Exception e){
            e.printStackTrace();
        }



        /**
         * 출력결과
         * java.lang.ClassNotFoundException: heesootory
         * 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
         * 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
         * 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
         * 	at java.base/java.lang.Class.forName0(Native Method)
         * 	at java.base/java.lang.Class.forName(Class.java:315)
         * 	at Main.method2(Main.java:8)
         * 	at Main.method1(Main.java:12)
         * 	at Main.main(Main.java:18)
         */


    }
}

```

> 예외를 던지는 과정에서 부모의 예외로 커지며 던졌다면, 그 부모를 받을 수 있는 예외까지 처리해 주어야 하기 때문에 부모의 Exception만 쓰거나, ClassNotFoundException와 Exception를 적어 주어야한다.

<br>
<br>
<br>

### UncheckedException은 throws를 안해도 알아서 던져진다.

```java
public class Main{

    static void method2(){  // throws ArithmeticException를 안해도 전달됨
        int i = 1/0;
    }

    static void method1(){  // throws ArithmeticException를 안해도 전달됨
        method2();
    }

    public static void main(String[] args){

        try{
            method1();
        }catch(ArithmeticException e){
            e.printStackTrace();
        }



        /**
         * 출력결과
         *  java.lang.ArithmeticException: / by zero
         * 	at Main.method2(Main.java:8)
         * 	at Main.method1(Main.java:12)
         * 	at Main.main(Main.java:18)
         */
    }
}
```

<br>
<br>
<br>
<br>

## 사용자 정의 예외

```java
public class PersonNotFoundException extends Exception{
    public PersonNotFoundException(String name){
        super(name + "에 해당하는 사람이 없습니다.");
    }
}
```
> PersonNotFoundException 이라는 에러를 class로 만들고, 생성자를 정의.

```java
public class Main{
    static String[] arr;
    static void foundPerson(String str) throws PersonNotFoundException {
        for(String s : arr){
            if(s.equals(str)) {
                System.out.println("존재하는 이름입니다.");
                return;     // 발견시 즉시 함수 종료
            }
        }
        throw new PersonNotFoundException(str);     
        // return이 되지않으면, Exception을 발생 시키고 던짐.
    }
    public static void main(String[] args){
        arr = new String[] {"hs", "yj", "cg", "sh"};

        try{
            foundPerson("oo");
        }catch(PersonNotFoundException e){
            e.printStackTrace();
        }

        /**
         * 출력결과
         *  PersonNotFoundException: oo에 해당하는 사람이 없습니다.
         * 	at Main.foundPerson(Main.java:14)
         * 	at Main.main(Main.java:20)
         */

    }
}
```
















